In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 45, 3)
arr2 = np.arange(50, 0, -5)

In [3]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

In [4]:
arr2

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5])

In [5]:
arr[5]
#seleciona o elemento no indice 5

15

In [6]:
arr[2:10]
#seleciona os elementos entre 2 e 10 sem incluir o 10

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [7]:
arr2[:8]
#seleciona ate o 8

array([50, 45, 40, 35, 30, 25, 20, 15])

In [8]:
arr2[4:10:2]
#começa no 4, vai ate o 10 e seleciona de 2 em 2

array([30, 20, 10])

In [9]:
arr[4:]
#seleciona do 4 em diante

array([12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

In [10]:
arr=np.arange(15).reshape(3,5)
#cria uma array numpy e redimensiona

In [11]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [12]:
arr2 = arr[:2]
#seleciona as primeiras duas linhas

In [13]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
arr2[:] = 21
#como arr2 contem as primeiras duas linhas de arr, substiui os valores por 21 tambem no arr

In [15]:
arr

array([[21, 21, 21, 21, 21],
       [21, 21, 21, 21, 21],
       [10, 11, 12, 13, 14]])

In [16]:
arr2 = arr[:1].copy()
#copia a primeira linha do arr para o arr2

In [17]:
arr2

array([[21, 21, 21, 21, 21]])

In [18]:
bol = arr > 20
#array booleano que tera o valor true para valores acima de 20 e false caso contrario

In [19]:
bol

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False]])

In [20]:
array = np.linspace(0, 20, 4)
#cria um array com valores igualmente espacados de acordo com os parametros

In [21]:
array

array([ 0.        ,  6.66666667, 13.33333333, 20.        ])

In [22]:
arr+arr2
#realiza a operacao de soma entre os 2 arrays

array([[42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [31, 32, 33, 34, 35]])

In [23]:
arr-arr
#realiza a subtracao

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [24]:
arr*arr2
#multiplicacao

array([[441, 441, 441, 441, 441],
       [441, 441, 441, 441, 441],
       [210, 231, 252, 273, 294]])

In [25]:
arr/arr2
#divisao

array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [0.47619048, 0.52380952, 0.57142857, 0.61904762, 0.66666667]])

In [26]:
arr*10
#multiplicacao por valor definido

array([[210, 210, 210, 210, 210],
       [210, 210, 210, 210, 210],
       [100, 110, 120, 130, 140]])

In [27]:
np.sqrt(arr)
#operacao de raiz

array([[4.58257569, 4.58257569, 4.58257569, 4.58257569, 4.58257569],
       [4.58257569, 4.58257569, 4.58257569, 4.58257569, 4.58257569],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [28]:
np.exp(arr2)
#exponencial

array([[1.31881573e+09, 1.31881573e+09, 1.31881573e+09, 1.31881573e+09,
        1.31881573e+09]])

In [29]:
np.cos(arr)
#tambem é possivel realizar operacoes trigonometricas

array([[-0.54772926, -0.54772926, -0.54772926, -0.54772926, -0.54772926],
       [-0.54772926, -0.54772926, -0.54772926, -0.54772926, -0.54772926],
       [-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722]])

In [30]:
np.max(arr)
#encontra o maior valor do array

21

In [31]:
np.min(arr)
#encontra o menor valor do array

10

É possível trasnformar listas comuns e matrizes em arrays numpy:

In [33]:
lista = [21, 29, 34, 56]

In [34]:
type(lista)

list

In [39]:
array = np.array(lista)
type(array)

numpy.ndarray

In [40]:
array

array([21, 29, 34, 56])

In [41]:
matriz = [[5, 10, 15], [2, 4, 6], [3, 6, 9]]

In [44]:
array_matriz = np.array(matriz)
type(array_matriz)

numpy.ndarray

In [45]:
array_matriz

array([[ 5, 10, 15],
       [ 2,  4,  6],
       [ 3,  6,  9]])

In [50]:
#criando uma matriz com zeros
arr = np.zeros((4,3))

In [51]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
#é possivel fazer o mesmo com '1'
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
#é possivel criar uma matriz identidade apenas com uma funcao
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [60]:
#criando um array numpy com valores aleatorios
np.random.rand(4)

array([0.49816862, 0.23055042, 0.8894232 , 0.8517923 ])

In [63]:
#matriz com valores aleatorios
np.random.rand(3,3)

array([[0.13521525, 0.1187621 , 0.78644247],
       [0.24714608, 0.34719331, 0.57053602],
       [0.30596933, 0.2291911 , 0.5055314 ]])

In [65]:
#criar array ou matriz apenas com valores inteiros
np.random.randint(0, 1000, 6)

array([821, 358, 333, 867, 773, 205])

In [67]:
#criar um array com valores que seguem uma distribuicao normal
arr = np.random.randn(4)

In [68]:
arr

array([-0.43774299, -0.1241286 ,  1.80608437,  0.09753061])

In [69]:
#encontra a posicao do vetor onde esta o maior elemento
arr.argmax()

2

In [70]:
#encontra a poiscao do vetor onde esta o menor elemento
arr.argmin()

0