In [21]:
import torch

In [22]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]])
x.shape

torch.Size([2, 4])

In [23]:
#multiplicação

x*10

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

In [24]:
#adição

x.add(10)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

In [25]:
x

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [28]:
#redimensionamento

x.view(4,2)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [30]:
#a função torch.ones cria um tensor com valores unitários

a = torch.ones(2,1,10)
a

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [35]:
#a função squeeze exclui as dimensões de tamanho 1

print(f'Shape antes de utilizar squeeze: {a.shape}')
squeezed = a.squeeze(1)
print(f'Shape depois de utilizar squeeze: {squeezed.shape}')

Shape antes de utilizar squeeze: torch.Size([2, 1, 10])
Shape depois de utilizar squeeze: torch.Size([2, 10])


In [36]:
a = torch.ones(2,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [39]:
#a função unsqueeze adiciona dimensões de tamanho 1

print(f'Shape antes de utilizar squeeze: {a.shape}')
squeezed = a.unsqueeze(2)
print(f'Shape depois de utilizar squeeze: {squeezed.shape}')

Shape antes de utilizar squeeze: torch.Size([2, 3])
Shape depois de utilizar squeeze: torch.Size([2, 3, 1])


In [40]:
#também é possível adicionar dimensões de tamanho 1 utilizando None

print(a[None].shape)
print(a[:,None].shape)
print(a[:,:,None].shape)

torch.Size([1, 2, 3])
torch.Size([2, 1, 3])
torch.Size([2, 3, 1])


In [41]:
#multiplicação de matrizes

x = torch.tensor([[1,2,3,4],[5,6,7,8]])
y = torch.tensor([[1,2,3],
                  [2,3,4],
                  [4,5,6],
                  [7,8,9]])

torch.matmul(x,y)

tensor([[ 45,  55,  65],
        [101, 127, 153]])

In [45]:
#concatenação

x = torch.randn(1,4,5)
z = torch.cat([x,x], axis=1)
print('Eixo 1 concatenado: ', x.shape, z.shape)

Eixo 1 concatenado:  torch.Size([1, 4, 5]) torch.Size([1, 8, 5])


In [46]:
#permutação

x = torch.randn(3,20,10)
z = x.permute(2,0,1)
print('Dimensões trocadas:', x.shape, z.shape)

Dimensões trocadas: torch.Size([3, 20, 10]) torch.Size([10, 3, 20])
